[package]
name = "naca"
version = "0.1.0"
edition = "2021"
default-run = "naca"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "anime"

[dependencies]
gnuplot = "0.0.37"
thiserror = "1.0.30"

[features]
